## How to stack/concatenate numpy arrays of any dimension

You have the following:
r_[]
c_[]
vstack()
hstack()
column_stack()
stack()
concatenate()


From <https://stackoverflow.com/questions/33356442/when-should-i-use-hstack-vstack-vs-append-vs-concatenate-vs-column-stack>

If you have two matrices, you're good to go with just `hstack` and `vstack`:

<img src="stacking/stack1.png" width="500" />


If you're stacking a matrice and a vector, `hstack` becomes tricky to use, so `column_stack` is a better option:

<img src="stacking/stack2.png" width="500" />


If you're stacking two vectors, you've got three options:

<img src="stacking/stack3.png" width="500" />


In [30]:
import numpy as np

a = np.arange(12).reshape(3,4)
b = np.arange(8).reshape(2,4)

print("All equivalent for stacking rows:")
print("vstack a + b:", np.vstack((a, b)), sep="\n", end="\n\n")
print("r_ a + b:", np.r_[(a, b)], sep="\n", end="\n\n")
print("concatenate a + b:", np.concatenate((a, b), axis=0), sep="\n", end="\n\n")


All equivalent for stacking rows:
vstack a + b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]]

r_ a + b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]]

concatenate a + b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]]



In [32]:
a = np.arange(12).reshape(3,4)
c = np.arange(6).reshape(3,2)

print("All equivalent for stacking columns:")
print("hstack a + c:", np.hstack((a, c)), sep="\n", end="\n\n")
print("column_stack a + c:", np.column_stack((a, c)), sep="\n", end="\n\n")
print("c_ a + c:", np.c_[(a, c)], sep="\n", end="\n\n")
print("concatenate a + c:", np.concatenate((a, c), axis=1), sep="\n", end="\n\n")


All equivalent for stacking columns:
hstack a + c:
[[ 0  1  2  3  0  1]
 [ 4  5  6  7  2  3]
 [ 8  9 10 11  4  5]]

column_stack a + c:
[[ 0  1  2  3  0  1]
 [ 4  5  6  7  2  3]
 [ 8  9 10 11  4  5]]

c_ a + c:
[[ 0  1  2  3  0  1]
 [ 4  5  6  7  2  3]
 [ 8  9 10 11  4  5]]

concatenate a + c:
[[ 0  1  2  3  0  1]
 [ 4  5  6  7  2  3]
 [ 8  9 10 11  4  5]]



In [44]:
a = np.arange(12).reshape(3,4)
b = np.arange(4)
c = np.arange(3)
print("When dealing with vectors and needing to add dims, we can't use concatenate or hstack.")
print("When mixing matrices and vectors, can't use stack or r_.")
print("vstack, a + b:", np.vstack((a, b)), sep="\n", end="\n\n")
# print("stack, a + b:", np.stack((a, b)), sep="\n", end="\n\n")
# print("concatenate a + b:", np.concatenate((a, b), axis=0), sep="\n", end="\n\n")
# print("r_, a + b:", np.r_[(a, b)], sep="\n", end="\n\n")

print("We can use c_ for mixing matrices and vectors.")
print("column_stack, a + c:", np.column_stack((a, c)), sep="\n", end="\n\n")
print("c_, a + c:", np.c_[(a, c)], sep="\n", end="\n\n")
# print("hstack, a + c:", np.stack((a, c)), sep="\n", end="\n\n")
# print("concatenate a + c:", np.concatenate((a, c), axis=1), sep="\n", end="\n\n")
# print("stack, a + c:", np.stack((a, c)), sep="\n", end="\n\n")



When dealing with vectors and needing to add dims, we can't use concatenate or hstack.
When mixing matrices and vectors, can't use stack or r_.
vstack, a + b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]

We can use c_ for mixing matrices and vectors.
column_stack, a + c:
[[ 0  1  2  3  0]
 [ 4  5  6  7  1]
 [ 8  9 10 11  2]]

c_, a + c:
[[ 0  1  2  3  0]
 [ 4  5  6  7  1]
 [ 8  9 10 11  2]]



In [17]:
a = np.arange(3)
b = np.arange(3, 6)
print("vstack, a + b:", np.vstack((a, b)), sep="\n", end="\n\n")
print("hstack, a + b:", np.hstack((a, b)), sep="\n", end="\n\n")
print("column_stack, a + b:", np.column_stack((a, b)), sep="\n", end="\n\n")

vstack, a + b:
[[0 1 2]
 [3 4 5]]

hstack, a + b:
[0 1 2 3 4 5]

column_stack, a + b:
[[0 3]
 [1 4]
 [2 5]]



In [12]:
# Use "stack" if you want to add a dimension (combine matrixes to sheets of matrixes)

a = np.arange(12).reshape(3,4)
b = np.zeros(12).reshape(3,4)
print("stack, a + b:", np.stack((a, b)), sep="\n", end="\n\n")



stack, a + b:
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]



In [23]:
a = np.arange(3)
b = np.arange(3, 6)
print("vstack, a + b:", np.vstack((a, b)), sep="\n", end="\n\n")
print("c_, a + b:", np.c_[(a, b)], sep="\n", end="\n\n")
print("stack, a + b:", np.stack((a, b), axis=1), sep="\n", end="\n\n")


vstack, a + b:
[[0 1 2]
 [3 4 5]]

c_, a + b:
[[0 3]
 [1 4]
 [2 5]]

stack, a + b:
[[0 3]
 [1 4]
 [2 5]]



In [21]:
a = np.arange(12).reshape(3,4)
b = np.arange(8).reshape(2,4)
c = np.arange(6).reshape(3,2)
print("r_, a + b:", np.r_[(a, b)], sep="\n", end="\n\n")
print("c_, a + c:", np.c_[(a, c)], sep="\n", end="\n\n")

vstack, a + b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]]

hstack, a + c:
[[ 0  1  2  3  0  1]
 [ 4  5  6  7  2  3]
 [ 8  9 10 11  4  5]]

