# Hello Numpy, Hello Pandas

## Numpy

A list is not just a list, it is an "ndarray" (n-dimensional array).

In [17]:
# Python
l = [
     [1,2,3],
     [4,5,6],
     [7,8,9]
    ]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
# Numpy
import numpy as np
# of course it can't be simple: the recommended constructor for an ndarray is actually "array"
a = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
             ])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
# Python
l[2]

[7, 8, 9]

In [26]:
# Numpy
a[2]

array([7, 8, 9])

In [27]:
l[2][1]

8

In [20]:
a[2][1]

8

In [28]:
l[2,1]

TypeError: list indices must be integers or slices, not tuple

In [29]:
a[2,1]

8

In [30]:
l[:,1]

TypeError: list indices must be integers or slices, not tuple

In [31]:
a[:,1]

array([2, 5, 8])

In [35]:
# Generating random ndarrays
# Fill with ints up to 10, 8 rows, 4 columns
X = np.random.randint(10, size=(8,4))
X

array([[5, 5, 3, 4],
       [8, 4, 9, 1],
       [6, 3, 5, 9],
       [9, 5, 1, 6],
       [4, 7, 5, 8],
       [8, 0, 2, 9],
       [9, 6, 8, 6],
       [6, 9, 7, 6]])

## Pandas

An ndarray is not just an ndarray, it is a dataframe.

In [37]:
import pandas as pd
df = pd.DataFrame(X, columns=['a','b','c','d'])
df

a  b  c  d
0  5  5  3  4
1  8  4  9  1
2  6  3  5  9
3  9  5  1  6
4  4  7  5  8
5  8  0  2  9
6  9  6  8  6
7  6  9  7  6

In [38]:
# Numpy
X[2]

array([9, 5, 1, 6])

In [40]:
# Pandas
# don't do 'df[2]' !
df.iloc[2]

a    6
b    3
c    5
d    9
Name: 2, dtype: int32

In [41]:
X[2,0]

6

In [42]:
df.iloc[2,0]

6

In [43]:
X[:,0]

array([5, 8, 6, 9, 4, 8, 9, 6])

In [44]:
df.iloc[:,0]

0    5
1    8
2    6
3    9
4    4
5    8
6    9
7    6
Name: a, dtype: int32